name: Kyma

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

concurrency:
  group: kyma-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

env:
  APP_NAME: bookshop-gha
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22
      - uses: ./.github/actions/kyma-setup
        with:
          buildpack-registry: ${{ vars.BUILDPACK_REGISTRY }}
          buildpack-registry-user: ${{ vars.USERNAME }}
          buildpack-registry-password: ${{ secrets.BUILDPACK_PASSWORD }}
          registry: ${{ vars.DOCKER_REGISTRY }}
          user: ${{ vars.USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          kube-config: ${{ secrets.KUBE_CONFIG }}
      - run: npm clean-install

      - run: npx cds up --to k8s

      - name: Upload resources folder as artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: html5-deployer-resources
          path: app/html5-deployer/resources/
          retention-days: 7

      # - uses: ./.github/actions/kyma-info
      #   if: always()
      #   with:
      #     app: ${{ env.APP_NAME }}
